cp -r ~/Downloads/i3dots-spiderman/.config/betterlockscreen ~/.config/
cp -r ~/Downloads/i3dots-spiderman/.config/picom ~/.config/
cp -r ~/Downloads/i3dots-spiderman/.config/nvim ~/.config/
cp -r ~/Downloads/i3dots-spiderman/.config/polybar/ ~/.config/
cp -r ~/Downloads/i3dots-spiderman/.config/rofi ~/.config/
cp -r ~/Downloads/i3dots-spiderman/.config/neofetch ~/.config
cp -r ~/Downloads/i3dots-spiderman/.config/kitty ~/.config/
cp -r ~/Downloads/i3dots-spiderman/.config/kitty/.zshrc ~/
cp -r ~/Downloads/i3dots-spiderman/.config/i3 ~/.config/
